spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_OAUTH2_CLIENT_ID}
            client-secret: ${DISCORD_OAUTH2_CLIENT_SECRET}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: identify
            client-name: Discord
        provider:
          discord:
            authorization-uri: https://discord.com/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            userNameAttribute: username
